/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaysToGiveRouteImport } from './routes/ways-to-give'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as OurImpactRouteImport } from './routes/our-impact'
import { Route as NewsAndEventsRouteImport } from './routes/news-and-events'
import { Route as MeetOurTeamRouteImport } from './routes/meet-our-team'
import { Route as HowWeWorkRouteImport } from './routes/how-we-work'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopOrderSuccessRouteImport } from './routes/shop/order-success'
import { Route as ShopCheckoutRouteImport } from './routes/shop/checkout'
import { Route as ShopCartRouteImport } from './routes/shop/cart'
import { Route as ShopSlugRouteImport } from './routes/shop/$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const WaysToGiveRoute = WaysToGiveRouteImport.update({
  id: '/ways-to-give',
  path: '/ways-to-give',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const OurImpactRoute = OurImpactRouteImport.update({
  id: '/our-impact',
  path: '/our-impact',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsAndEventsRoute = NewsAndEventsRouteImport.update({
  id: '/news-and-events',
  path: '/news-and-events',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetOurTeamRoute = MeetOurTeamRouteImport.update({
  id: '/meet-our-team',
  path: '/meet-our-team',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeWorkRoute = HowWeWorkRouteImport.update({
  id: '/how-we-work',
  path: '/how-we-work',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopOrderSuccessRoute = ShopOrderSuccessRouteImport.update({
  id: '/shop/order-success',
  path: '/shop/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/shop/checkout',
  path: '/shop/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/shop/cart',
  path: '/shop/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/meet-our-team': typeof MeetOurTeamRoute
  '/news-and-events': typeof NewsAndEventsRoute
  '/our-impact': typeof OurImpactRoute
  '/our-story': typeof OurStoryRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/volunteer': typeof VolunteerRoute
  '/ways-to-give': typeof WaysToGiveRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/order-success': typeof ShopOrderSuccessRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/meet-our-team': typeof MeetOurTeamRoute
  '/news-and-events': typeof NewsAndEventsRoute
  '/our-impact': typeof OurImpactRoute
  '/our-story': typeof OurStoryRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/volunteer': typeof VolunteerRoute
  '/ways-to-give': typeof WaysToGiveRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/order-success': typeof ShopOrderSuccessRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/meet-our-team': typeof MeetOurTeamRoute
  '/news-and-events': typeof NewsAndEventsRoute
  '/our-impact': typeof OurImpactRoute
  '/our-story': typeof OurStoryRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/volunteer': typeof VolunteerRoute
  '/ways-to-give': typeof WaysToGiveRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/order-success': typeof ShopOrderSuccessRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/donate'
    | '/events'
    | '/gallery'
    | '/how-we-work'
    | '/meet-our-team'
    | '/news-and-events'
    | '/our-impact'
    | '/our-story'
    | '/partners'
    | '/privacy'
    | '/programs'
    | '/sitemap.xml'
    | '/success-stories'
    | '/terms'
    | '/volunteer'
    | '/ways-to-give'
    | '/dashboard'
    | '/shop/$slug'
    | '/shop/cart'
    | '/shop/checkout'
    | '/shop/order-success'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/donate'
    | '/events'
    | '/gallery'
    | '/how-we-work'
    | '/meet-our-team'
    | '/news-and-events'
    | '/our-impact'
    | '/our-story'
    | '/partners'
    | '/privacy'
    | '/programs'
    | '/sitemap.xml'
    | '/success-stories'
    | '/terms'
    | '/volunteer'
    | '/ways-to-give'
    | '/dashboard'
    | '/shop/$slug'
    | '/shop/cart'
    | '/shop/checkout'
    | '/shop/order-success'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/donate'
    | '/events'
    | '/gallery'
    | '/how-we-work'
    | '/meet-our-team'
    | '/news-and-events'
    | '/our-impact'
    | '/our-story'
    | '/partners'
    | '/privacy'
    | '/programs'
    | '/sitemap.xml'
    | '/success-stories'
    | '/terms'
    | '/volunteer'
    | '/ways-to-give'
    | '/_authenticated/dashboard'
    | '/shop/$slug'
    | '/shop/cart'
    | '/shop/checkout'
    | '/shop/order-success'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  HowWeWorkRoute: typeof HowWeWorkRoute
  MeetOurTeamRoute: typeof MeetOurTeamRoute
  NewsAndEventsRoute: typeof NewsAndEventsRoute
  OurImpactRoute: typeof OurImpactRoute
  OurStoryRoute: typeof OurStoryRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramsRoute: typeof ProgramsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  TermsRoute: typeof TermsRoute
  VolunteerRoute: typeof VolunteerRoute
  WaysToGiveRoute: typeof WaysToGiveRoute
  ShopSlugRoute: typeof ShopSlugRoute
  ShopCartRoute: typeof ShopCartRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopOrderSuccessRoute: typeof ShopOrderSuccessRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ways-to-give': {
      id: '/ways-to-give'
      path: '/ways-to-give'
      fullPath: '/ways-to-give'
      preLoaderRoute: typeof WaysToGiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-impact': {
      id: '/our-impact'
      path: '/our-impact'
      fullPath: '/our-impact'
      preLoaderRoute: typeof OurImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-and-events': {
      id: '/news-and-events'
      path: '/news-and-events'
      fullPath: '/news-and-events'
      preLoaderRoute: typeof NewsAndEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet-our-team': {
      id: '/meet-our-team'
      path: '/meet-our-team'
      fullPath: '/meet-our-team'
      preLoaderRoute: typeof MeetOurTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-work': {
      id: '/how-we-work'
      path: '/how-we-work'
      fullPath: '/how-we-work'
      preLoaderRoute: typeof HowWeWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/order-success': {
      id: '/shop/order-success'
      path: '/shop/order-success'
      fullPath: '/shop/order-success'
      preLoaderRoute: typeof ShopOrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/checkout': {
      id: '/shop/checkout'
      path: '/shop/checkout'
      fullPath: '/shop/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/cart': {
      id: '/shop/cart'
      path: '/shop/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  HowWeWorkRoute: HowWeWorkRoute,
  MeetOurTeamRoute: MeetOurTeamRoute,
  NewsAndEventsRoute: NewsAndEventsRoute,
  OurImpactRoute: OurImpactRoute,
  OurStoryRoute: OurStoryRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramsRoute: ProgramsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  TermsRoute: TermsRoute,
  VolunteerRoute: VolunteerRoute,
  WaysToGiveRoute: WaysToGiveRoute,
  ShopSlugRoute: ShopSlugRoute,
  ShopCartRoute: ShopCartRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopOrderSuccessRoute: ShopOrderSuccessRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
